# Generated by Django 5.2.6 on 2025-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('pomodoro', 'Pomodoro'), ('focus', 'Focus'), ('break', 'Break')], default='pomodoro', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('planned_duration', models.IntegerField(help_text='Duration in minutes')),
                ('actual_duration', models.IntegerField(blank=True, help_text='Actual duration in minutes', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FocusSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sound_file', models.FileField(upload_to='focus_sounds/')),
                ('category', models.CharField(default='nature', max_length=50)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFocusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoro_duration', models.IntegerField(default=25, help_text='Minutes')),
                ('short_break_duration', models.IntegerField(default=5, help_text='Minutes')),
                ('long_break_duration', models.IntegerField(default=15, help_text='Minutes')),
                ('sessions_before_long_break', models.IntegerField(default=4)),
                ('auto_start_breaks', models.BooleanField(default=False)),
                ('auto_start_pomodoros', models.BooleanField(default=False)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
