# Generated by Django 5.2.6 on 2025-09-28 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='user_assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessment.userassessment'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='user_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.userassessment'),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresponse',
            unique_together={('user_assessment', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyprogress',
            unique_together={('user', 'week_start_date')},
        ),
    ]
