# Generated by Django 5.2.6 on 2025-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('focus_sessions_completed', models.IntegerField(default=0)),
                ('total_focus_time', models.IntegerField(default=0, help_text='Minutes')),
                ('focus_sessions_goal', models.IntegerField(default=0)),
                ('medications_taken', models.IntegerField(default=0)),
                ('medications_scheduled', models.IntegerField(default=0)),
                ('medication_adherence_rate', models.FloatField(default=0.0)),
                ('activities_completed', models.IntegerField(default=0)),
                ('activities_scheduled', models.IntegerField(default=0)),
                ('activity_completion_rate', models.FloatField(default=0.0)),
                ('points_earned_today', models.IntegerField(default=0)),
                ('points_spent_today', models.IntegerField(default=0)),
                ('total_available_points', models.IntegerField(default=0)),
                ('mood_score', models.FloatField(blank=True, help_text='1-5 scale', null=True)),
                ('energy_level', models.FloatField(blank=True, help_text='1-5 scale', null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('sleep_quality', models.FloatField(blank=True, help_text='1-5 scale', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('focus_trends', 'Focus Trends'), ('medication_adherence', 'Medication Adherence'), ('weekly_progress', 'Weekly Progress'), ('upcoming_activities', 'Upcoming Activities'), ('points_summary', 'Points Summary'), ('recent_achievements', 'Recent Achievements'), ('mood_tracker', 'Mood Tracker'), ('quick_actions', 'Quick Actions')], max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('reminder', 'Reminder')], default='info', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_global', models.BooleanField(default=False, help_text='Show to all users')),
                ('action_url', models.URLField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(default=dict, help_text='Dashboard layout configuration')),
                ('theme', models.CharField(default='light', max_length=20)),
                ('refresh_interval', models.IntegerField(default=300, help_text='Seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.JSONField(help_text='x, y, width, height')),
                ('config', models.JSONField(default=dict, help_text='Widget-specific configuration')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
