# Generated by Django 5.2.6 on 2025-09-28 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='user_medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medication.usermedication'),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='user_medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medication.usermedication'),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='user_medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medication.usermedication'),
        ),
    ]
